[WIP]情報交換ページの実装
yuri2509/mamorukun pull request #12
Opened 2020-12-28 04:29 UTC by yuri2509

2021-01-13 14:43 UTC, EL93019205 commented
LGTM!!!

2021-02-04 09:34 UTC, yukeippi requested changes
全体的には問題ないと思います。
気になったのはredirect_toとrenderの使い方です。
このあたりをご説明します。

2021-02-04 09:34 UTC, yukeippi commented on app/controllers/messages_controller.rb
> +      redirect_to messages_path, notice: 'メッセージを入力してください。', status: :bad_request
messageのcontentがブランクの場合はエラーが発生します。

通常はエラーが発生すると、入力画面に戻ってエラーメッセージを表示するのですが、項目が複数ある場合は各項目事にエラーを出したりするので、redirect_toではなく、renderを使います。redirect_toを使うと、セッションが切れてしまうので、エラー情報を引き渡せなくなります。

2021-02-04 09:34 UTC, yukeippi commented on app/controllers/messages_controller.rb
> +  end
使用しないメソッドは削除した方がいいかもです。

2021-02-04 09:34 UTC, yukeippi commented on app/controllers/messages_controller.rb
> +    end
ここは@message（インスタンス変数）である必要はありません。
messageの方が望ましいです。

2021-02-04 09:34 UTC, yukeippi commented on spec/requests/messages_spec.rb
> +      it "200レスポンスが返ってきていること" do
ちょっとインデントがずれています。

2021-02-04 09:34 UTC, yukeippi commented on spec/requests/messages_spec.rb
> +      it "200レスポンスが返ってきていること" do
ちょっとインデントがずれています。

2021-02-04 11:18 UTC, yukeippi reviewed
２件ほどテストの記述が足りない部分があります。
追記します。

2021-02-04 11:18 UTC, yukeippi commented on spec/requests/messages_spec.rb
> +        end
テストの記述が途中です。
```
expect do
  post messages_url, params: { message: FactoryBot.attributes_for(:message, content: nil) }
end.to change { Message.count }.by(0)
```

2021-02-04 11:18 UTC, yukeippi commented on spec/requests/messages_spec.rb
> +      end
ここも途中です。

2021-02-04 12:53 UTC, yuri2509 commented on app/controllers/messages_controller.rb
> +      redirect_to messages_path, notice: 'メッセージを入力してください。', status: :bad_request
renderに修正しました

2021-02-04 12:53 UTC, yuri2509 commented on app/controllers/messages_controller.rb
> +  end
削除しました

2021-02-04 12:53 UTC, yukeippi commented
LGTM！

2021-02-04 12:53 UTC, yuri2509 commented on app/controllers/messages_controller.rb
> +    end
インスタンス変数から変数に変更しました

2021-02-04 12:54 UTC, yuri2509 commented on spec/requests/messages_spec.rb
> +      it "200レスポンスが返ってきていること" do
修正しました

2021-02-04 12:54 UTC, yuri2509 commented on spec/requests/messages_spec.rb
> +      it "200レスポンスが返ってきていること" do
上記と同じです

2021-02-04 12:54 UTC, yuri2509 commented on spec/requests/messages_spec.rb
> +        end
修正しました

2021-02-04 12:54 UTC, yuri2509 commented on spec/requests/messages_spec.rb
> +      end
修正しました

2021-02-04 13:00 UTC, merged